const ActionTypes = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS : 'SIGNUP_REQUEST_SUCCESS',

    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS : 'LOGIN_REQUEST_SUCCESS'
}

export default ActionTypes;